a="GACATATACTCATAAATTCCGGAATGCTTCCTGAGTTGTCCTGTTTAACGATGGGTAACCTCACTCGGCACGCGAAGGTTATATCCAAGGATAGGCTGTGGGACGCATTTCTGCCCTACTGTGTAGATCACAATAATCCCATGTCTTACCCTCCACATCTGTCAGTAAATAGGGCGTTTACTTGGGACACCACGCCTGGCTTTGAGCTGAGTGTGTTATGAGTCTCACGTGAGCTAAACATGCCTGGCTGTCTGTGTGTTTCCAACCGTTTTTAGTAAGGGGCCTTTGACCCGGATGGCGGGTTCCTAGTAAACTTGGTTCCATAGCTTCGGGTTATGCTTGGACGTGGTGACTCTATTGAAACGTGGCTACGCCTACGCGGCAAAAGTCCACCGGATCATTATATTCAGGAAGTTGGGTAGACTATGGCTACCATTAATTTTCTGGTACCCAGTATGAAGGGCGACATGGTCTATTTCGGGTTCCTTGGCGTCCTTGATGTCATCCTGCGTCTGACAGGGGCCATGGTGAGTTTGTGGGGGTTGACCACGGCTTTGTTCAGTATCCTTAAGTGTTGTACACCGTATCTTTAGGGCGTTACCCGCCCCGGAAGCCTCTTAGAGGATTCACCCCGGTACACTCGTGAATTGCTGGCTCTCACCCCGGAGTGTCGTGTAGTAACATGCAGTGATTCGTACGTTAGGTGCTGCCTGGTAACGTTCTAAGGAGCATTCGACATGCTAAGGGGCCATCAGGACCTGGCCTCGCTACAAACGACATAGTTTGTCCTCATATACGTTGATTCAATACTTCGAGGGTATCTAACTAGTAATCCCCAAGTAAGGGTTGACTCATACAACTTGCTCGCAGCGCTGCGGAGATGCGTGTATTGGAGGGCCCGTAGCAACGCCATGCGAAATGTAACACCATTCAATCTGTAAACATCCAGAGGTCGCCATAATACCAC"
b=[]
for i in a:
    if i == "A":
        b.append("T")
    elif i == "T":
        b.append("A")
    elif i == "C":
        b.append("G")
    elif i == "G":
        b.append("C")
b.reverse()
ans = "".join(b)
print(ans)